#!/bin/bash

#   run an ansible playbook on a set of AWS hosts (ex: stage, prod, or all)

#   args
target=${2:-all}
scriptname=$1

#   state
currentbranch="$(git rev-parse --abbrev-ref @)"

#   commands
one="ansible-playbook"
two="-i $PWD/deploy/$target.inventory --vault-password-file deploy/private/vault_pass.txt"
echo $one $two "deploy/$scriptname.yml" --extra-vars "{target: \"$target\", currentbranch: \"$currentbranch\", operator: \"$USER\", operator_machine: \"$(hostname)\"}"
exec $one $two "deploy/$scriptname.yml" --extra-vars "{target: \"$target\", currentbranch: \"$currentbranch\", operator: \"$USER\", operator_machine: \"$(hostname)\"}"
