#!/bin/bash

#   encrypt all files that:
#   1. are in deploy AND end in .yml AND
#   2. match private.yml OR *.private.yml OR *.private.*.yml OR
#   3. are in a folder called private/

source .git/crypt.sh

for fyle in ${private_files[@]}
do
    if ! file_is_already_encrypted $fyle; then
        target_files+=("$fyle")
    fi
done

if [ ${#target_files[@]} -gt 0 ]; then
    echo 'encrypting these files:'
    echo ${target_files[@]} | tr ' ' '\n'
    ansible-vault --vault-password-file=$vault_password_file encrypt ${target_files[@]}
else
    echo 'there were no files to encrypt'
fi
