#!/bin/bash

#   run ad-hoc shell commands against sets of hosts on AWS

one=ansible
hosts=$1
shift
two="-i $PWD/deploy/inventories/aws $hosts -m shell -a"
three=$@
echo $one $two "$three"
exec $one $two "$three"
