#!/bin/bash

#   run ad-hoc shell commands against sets of hosts on AWS

one=ansible
target=${1:-all}
shift
two="-i $PWD/deploy/all.inventory $target -m shell -a"
three=$@
echo $one $two "$three"
exec $one $two "$three"
