#!/bin/bash

#   print a summary of all encrypted files and eligible plain-text files

source .git/crypt.sh

not_encrypted=()
for fyle in ${private_files[@]}
do
    if [ "$(file -b $fyle)" != "directory" ]; then
        if file_is_already_encrypted $fyle; then
            target_files+=("$fyle")
        else
            not_encrypted+=("$fyle")
        fi
    fi
done
if [ ${#target_files[@]} -gt 0 ]; then
    echo 'these files are encrypted:'
    echo ${target_files[@]} | tr ' ' '\n'
fi
if [ ${#not_encrypted[@]} -gt 0 ]; then
    echo
    echo 'these files are not encrypted:'
    echo ${not_encrypted[@]} | tr ' ' '\n'
fi
